package.path = package.path .. ';src/?.lua'
package.path = package.path .. ';src/Assets/?.lua'
package.path = package.path .. ';src/Engine/?.lua'
package.path = package.path .. ';src/GameObjects/?.lua'
package.path = package.path .. ';src/Mesh/?.lua'