-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:0dab6ca8bb5062c095595a510d533ea9$
-- 

return {
	texture = 'BGSheet.png',
	frames = {
			{
				name = "bg.png",
				spriteColorRect = { x = 0, y = 0, width = 1028, height = 772 },
				uvRect = { u0 = 0.000976562, v0 = 0.00195312, u1 = 0.50293, v1 = 0.755859 },
				spriteSourceSize = { width = 1028, height = 772 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

