-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:08883ba325930d0f6617dfe899052e21$
-- 

return {
	texture = 'MainSheet.png',
	frames = {
			{
				name = "enemy.png",
				spriteColorRect = { x = 0, y = 0, width = 146, height = 128 },
				uvRect = { u0 = 0.00195312, v0 = 0.000976562, u1 = 0.144531, v1 = 0.0634766 },
				spriteSourceSize = { width = 146, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "lightsquare.png",
				spriteColorRect = { x = 0, y = 0, width = 926, height = 928 },
				uvRect = { u0 = 0.00195312, v0 = 0.0644531, u1 = 0.90625, v1 = 0.517578 },
				spriteSourceSize = { width = 926, height = 928 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "moai.png",
				spriteColorRect = { x = 0, y = 0, width = 260, height = 260 },
				uvRect = { u0 = 0.00195312, v0 = 0.518555, u1 = 0.255859, v1 = 0.645508 },
				spriteSourceSize = { width = 260, height = 260 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "moai2.png",
				spriteColorRect = { x = 0, y = 0, width = 260, height = 260 },
				uvRect = { u0 = 0.257812, v0 = 0.518555, u1 = 0.511719, v1 = 0.645508 },
				spriteSourceSize = { width = 260, height = 260 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "player.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 123 },
				uvRect = { u0 = 0.513672, v0 = 0.518555, u1 = 0.589844, v1 = 0.578613 },
				spriteSourceSize = { width = 78, height = 123 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playerthingy.png",
				spriteColorRect = { x = 0, y = 0, width = 59, height = 57 },
				uvRect = { u0 = 0.591797, v0 = 0.518555, u1 = 0.649414, v1 = 0.546387 },
				spriteSourceSize = { width = 59, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "whiterectangle.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 14 },
				uvRect = { u0 = 0.651367, v0 = 0.518555, u1 = 0.704102, v1 = 0.525391 },
				spriteSourceSize = { width = 54, height = 14 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "whitesquare.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 54 },
				uvRect = { u0 = 0.706055, v0 = 0.518555, u1 = 0.758789, v1 = 0.544922 },
				spriteSourceSize = { width = 54, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

