-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:bfe5d7bfba25bec0ed436b91c368ab2c$
-- 

return {
	texture = 'MainSheet.png',
	frames = {
			{
				name = "bloodvessel.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 19 },
				uvRect = { u0 = 0.00390625, v0 = 0.00195312, u1 = 0.101562, v1 = 0.0205078 },
				spriteSourceSize = { width = 50, height = 19 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bullet.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 23 },
				uvRect = { u0 = 0.105469, v0 = 0.00195312, u1 = 0.154297, v1 = 0.0244141 },
				spriteSourceSize = { width = 25, height = 23 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "enemy.png",
				spriteColorRect = { x = 0, y = 0, width = 146, height = 128 },
				uvRect = { u0 = 0.158203, v0 = 0.00195312, u1 = 0.443359, v1 = 0.126953 },
				spriteSourceSize = { width = 146, height = 128 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "moai.png",
				spriteColorRect = { x = 0, y = 0, width = 260, height = 260 },
				uvRect = { u0 = 0.447266, v0 = 0.00195312, u1 = 0.955078, v1 = 0.255859 },
				spriteSourceSize = { width = 260, height = 260 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "moai2.png",
				spriteColorRect = { x = 0, y = 0, width = 260, height = 260 },
				uvRect = { u0 = 0.00390625, v0 = 0.257812, u1 = 0.511719, v1 = 0.511719 },
				spriteSourceSize = { width = 260, height = 260 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "player.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 123 },
				uvRect = { u0 = 0.515625, v0 = 0.257812, u1 = 0.667969, v1 = 0.37793 },
				spriteSourceSize = { width = 78, height = 123 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "playerthingy.png",
				spriteColorRect = { x = 0, y = 0, width = 59, height = 57 },
				uvRect = { u0 = 0.671875, v0 = 0.257812, u1 = 0.787109, v1 = 0.313477 },
				spriteSourceSize = { width = 59, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "whiterectangle.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 14 },
				uvRect = { u0 = 0.791016, v0 = 0.257812, u1 = 0.896484, v1 = 0.271484 },
				spriteSourceSize = { width = 54, height = 14 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "whitesquare.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 54 },
				uvRect = { u0 = 0.00390625, v0 = 0.513672, u1 = 0.109375, v1 = 0.566406 },
				spriteSourceSize = { width = 54, height = 54 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

